In [1]:
import numpy as np

In [2]:
a=np.array([1,34,45,88])

In [3]:
a

array([ 1, 34, 45, 88])

In [4]:
b=np.array([45,27,57,69])

In [5]:
b

array([45, 27, 57, 69])

In [6]:
print(a)

[ 1 34 45 88]


In [7]:
print(b)

[45 27 57 69]


In [8]:
# 2d array
i=np.array([[12,3],[22,6],[56,3]])

In [11]:
print(i)

[[12  3]
 [22  6]
 [56  3]]


In [12]:
i[0]

array([12,  3])

In [13]:
i[0][1]

3

In [14]:
i*3

array([[ 36,   9],
       [ 66,  18],
       [168,   9]])

In [15]:
i+3

array([[15,  6],
       [25,  9],
       [59,  6]])

In [21]:
i[0:3]

array([[12,  3],
       [22,  6],
       [56,  3]])

In [17]:
i[0:1]

array([[12,  3]])

In [19]:
i[0:2,0:1]

array([[12],
       [22]])

In [20]:
i.shape

(3, 2)

In [30]:
j=np.array([[13,5],[87,4],[23,9]])
print(j)

[[13  5]
 [87  4]
 [23  9]]


In [31]:
j/4

array([[ 3.25,  1.25],
       [21.75,  1.  ],
       [ 5.75,  2.25]])

In [32]:
j[:,1]

array([5, 4, 9])

In [33]:
print(j[0:1,1])

[5]


In [34]:
j.dtype

dtype('int64')

In [39]:
j.max()

87

In [40]:
j.min()

4

In [41]:
j.reshape(2,3)

array([[13,  5, 87],
       [ 4, 23,  9]])

In [45]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
np.full([3,3],8.2)

array([[8.2, 8.2, 8.2],
       [8.2, 8.2, 8.2],
       [8.2, 8.2, 8.2]])

In [48]:
np.ones([4,4],dtype='int32')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)

In [49]:
np.add(i,j)

array([[ 25,   8],
       [109,  10],
       [ 79,  12]])

In [50]:
j1=j*2

In [51]:
j1

array([[ 26,  10],
       [174,   8],
       [ 46,  18]])

In [52]:
j2=j+10

In [53]:
j2

array([[23, 15],
       [97, 14],
       [33, 19]])